# Spring properties
spring:
  application:
     name: zuul-gateway  # Service registers under this name


zuul:
  ignoredServices: "*"
#  routes:
#    productcomposite:
#      path: /*/**

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333 # HTTP  port