# Spring properties
spring:
  application:
     name: zuul-gateway  # Service registers under this name

#
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    products-service: #this should match the spring.application.name of the spring boot app (defined in its own yml)
      path: /products/** # this is where is going to redirect to.

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: fernando
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8080/uaa/user

# HTTP Server
server:
  port: 3131 # HTTP  port

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

