# Spring properties
spring:
  application:
     name: zuul-gateway  # Service registers under this name

#zuul:
#  ignoredServices: "*"
#  routes:
#    products-service: #this should match the spring.application.name of the spring boot app (defined in its own yml)
#      path: /products/**
#      url: http://localhost:4444
#    user:
#      path: /user/**
#      url: http://localhost:8081/uaa/user


zuul:
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:8081/spring-security-oauth-server/oauth


# HTTP Server
server:
  port: 8080 # HTTP  port

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


#facebook:
#  client:
#    clientId: 233668646673605
#    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    #resource offered by facebook and consumed by our client app
#    userInfoUri: https://graph.facebook.com/me
#
#github:
#  client:
#    clientId: bd1c0a783ccdd1c9b9e4
#    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user

#zuul acts as a client for the oauth server (it is the only oauth client). Products Services is the Resource
#security:
#  oauth2:
#    client:
#      client-id: zuulclient
#      client-secret: zuulsecret
#      scope: read,write
#      auto-approve-scopes: '.*'
#      authorized-grant-types: authorization_code,refresh_token,password
#      userAuthorizationUri: http://localhost:8081/spring-security-oauth-server/oauth
#      accessTokenUri: http://localhost:8081/spring-security-oauth-server/access_token
#  user:
#    password: password

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
