# Spring properties
spring:
  application:
     name: zuul-gateway  # Service registers under this name

zuul:
  ignoredServices: "*"
  routes:
    products-service: #this should match the spring.application.name of the spring boot app (defined in its own yml)
      path: /products/**
      url: http://localhost:4444
    user:
      path: /user/**
      url: http://localhost:8080/uaa/user


# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3131 # HTTP  port


security:
  user:
    password: welcome
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
    resource:
      userInfoUri: http://localhost:8080/uaa/user

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
