# Spring properties
spring:
  application:
     name: products-service  # Service registers under this name


# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 6666   # HTTP (Tomcat) port