# Spring properties
spring:
  application:
     name: authorization-server  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/authorization-server/templates/    # Trailing / mandatory
                             # Template location for this application only

# Map the error path to error template
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  #todo do not use hardcoded ports?

#application:
#  directorypath: c://Test
