# Spring properties
spring:
  application:
     name: core-server  # Service registers under this name
#  freemarker:
#    enabled: false           # Ignore Eureka dashboard FreeMarker templates
#  thymeleaf:
#    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
#    prefix: classpath:/core-server/templates/    # Trailing / mandatory
#                             # Template location for this infra only

# Map the error path to error template
error:
  path=/error

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


security:
  user:
    password: welcome

# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port