# Spring properties
spring:
  application:
     name: products-service  # Service registers under this name

# Map the error path to error template
error:
  path=/error

# Discovery Server Access
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port
  context-path: /products

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/me


#infra:
#  directorypath: c://Test
